FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y \
      python3 \
      python3-venv \
      sqlite3 \
      curl \
      build-essential \
      gdb \
      unzip \
      direnv \
      time \
      ripgrep
